export const MSG_FROM_SERVER = {
    YOU_CONNECTED: 'YOU_CONNECTED',
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    OFFER_CREATED: 'OFFER_CREATED',
    ANSWER_CREATED: 'ANSWER_CREATED'
} as const;

export type WsActionFromServer = (typeof MSG_FROM_SERVER)[keyof typeof MSG_FROM_SERVER];
