export const MSG_FROM_SERVER = {
    YOU_CONNECTED: 'YOU_CONNECTED',
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    INCOMING_OFFER: 'INCOMING_OFFER',
    INCOMING_ANSWER: 'INCOMING_ANSWER',
    USER_TOGGLED_MIC: 'USER_TOGGLED_MIC'
} as const;

export type WsActionFromServer = (typeof MSG_FROM_SERVER)[keyof typeof MSG_FROM_SERVER];
